### ISSUE TITLE
Implement Zserio wrapper types in the runtime library

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio-cpp17#2]
Implement Zserio C++ wrapper types in the runtime library for all available Zserio types according to the [Design Document](https://github.com/ndsev/zserio-cpp17/blob/master/doc/Cpp17Design.md#built-in-types).

Effort: 5md

**Comment by Mi-La** [comment]
Update also related runtime utilities like BitSizeOfCalculator, BitStreamWriter, BitStreamReader, etc.

**Comment by Mi-La** [comment]
The `Integer` wrapper type from PoC has implicit constructor: https://github.com/ndsev/zserio-cpp17/blob/82542c92ca9f04ca74f8d4ea37e173f9235e3f8d/poc/runtime/zserio/TypeWrappers.h#L43-L45 

E.g. for `Int8`, it allows implicit conversion from integer literal (which is basically `int`). In case that the literal is greater than `INT8_MAX`, we only get compile time warning (if enabled) about `implicit conversion from 'int' to ... changes value from ...`. In case of clang this is warning `-Wconstant-conversion`.

Is this enough or do we need to somehow handle range checking in this case? Any ideas?

**Comment by Mi-La** [comment]
Test cases which doesn't work (tested with clang-14):

**1. Ternary operator with different types:**
```
Int64 i64{}
Int32 i32{};

static Int64 get(Int64 i64, Int32 i32, bool condition)
{
    return condition ? i64 : i32;
}
```

  * We get error:
```
error: conditional expression is ambiguous; 'IntWrapper<int64_t, 64>' can be converted to 'IntWrapper<int32_t, (default) 8 * sizeof(VALUE_TYPE) aka 32>' and vice versa
```

  * Solution:
We have to add `static_cast` to have the same types in both branches which could be difficult in generated code since generator doesn't know the exact type of expressions.
We will probably need something like this to be called for each branch of ternary operator:
```
template <typename T>
typename T::value_type to_value(T wrapper)
{
    return wrapper; // causes conversion of any wrapped type to it's value type
};
```

**2. Suppressing of warnings during type conversions:**
```
Float16 f16{};
Int16 i16 = f16;
```

  * We get warning:
```
warning: implicit conversion turns floating-point number into integer: 'zserio::detail::NumericTypeWrapper<float>::value_type' (aka 'float') to 'zserio::detail::NumericTypeWrapper<short>::value_type' (aka 'short') [-Wfloat-conversion]
```

  * Solution:
With built-in types we would just add `static_cast<int16_t>(f16)`, so with the wrappers types we would expect that `static_cast<Int16>(f16)` will work. But it doesn't suppress the warning. Instead we still have to use static cast with built-in `int16_t`.
We could also invent custom  `zserio_static_cast` which would force static_cast on the values types:
```
template <typename T, typename V>
constexpr T zserio_static_cast(zserio::detail::NumericTypeWrapper<V> wrapper) noexcept
{
    return static_cast<typename T::value_type>(wrapper);
}
```
