### ISSUE TITLE
Implement Zserio variant in the runtime library

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio-cpp17#4]
Implement Zserio variant in the runtime library according to the [Design Document](https://github.com/ndsev/zserio-cpp17/blob/master/doc/Cpp17Design.md#choice-and-union-types).

Effort: 5md

**Comment by mikir** [comment]
Thanks a  lot for sharing the idea and for the example.

If we got it correctly, we can see two problems with the suggested solution:

- Method `index()` returns `size_t` instead of corresponding enumeration which is inconsistent and unintuitive for users.
- Variant needs some empty state (monostate) inside because of cases without any field:
  ```
  choice UInt16ParamChoice(uint16 selector) on selector
  {
      case 1:
          VariantA  valueA;

      case 2:
          VariantB  valueB;

      case 5:
      case 6:
          // empty
          ;

      default:
          VariantC  valueC;
  };
  ```
  Users will have to set somehow empty variant which it could be in this case one monostate. This monostate can be used for uninitialized state as well. In other words, we suggest to have always one monostate just because of these use cases. The only use case when monostate is probably not needed (this is valid only if empty constructor will be always generated) is the choice without any empty cases. However, it is good to use monostate even for this use case just because of schema evolution (one can add new case without any field and break application). Moreover, this monostate solution is used in standard library, so it might be more understable for newcomers.

**Comment by reinco** [comment]
1. In the zserio variant, of course index() should return the Enum, not a size_t. (it can have a different name is needed).
2. There is a difference between: 
    1. unitialized variant (use hidden tag struct Unitialized, see example). It is an error to write this to a blob, validate fails.
    2.  and fields who have explicit empty data using zserio type 'flag' (use zserio::Flag in c++).  Not an error.
    3. fields which happen to have no data (use zserio::Flag as well). Not an error.
    4. So you cannot use monostate for all of the 3 cases, although std::monostate can serve as baseclass to zserio::Flag as in my example and also monostate can be a base of Unitialized if you want to make that type public.
 3. Unitialized may happen in 3 cases only: a move assignment from another variant, default construction, move construction from another variant. I was in favor not to expose this unless really needed for some functionality: in reader code a variant should never be in Unassigned state, unless someone forgot decode the blob into the Data class. So in general users should not have to worry or write code to deal with Unitialized.
 4. Be careful in the implementation if you want to use std::variant or similar code internally: there were some known issues in the past that std::variant is O(k) where k = amount of variants. Since k is large in nds this may be a problem. To have efficient code you need to ensure that an O(1) lookup for visit, comparison, destruction is possible. This can be done for example by emitting static lookup tables from index to compare/destroy functions. A good compiler, linker would generate a lookup automatically but some older compilers do have issues doing this.

**Comment by mikir** [comment]
I think the important question here is: "Do we really need to distinguish between uninitialized and empty states?" Is it worth to over complicate variant just because of uninitialized state which is not needed at all during reading?

Consider different data types (arrays, enumerations, bitmasks, integers), none of them will have something like uninitialized state. Is really variant something special here? I think if uninitialized state is a problem, we should solve this consistently for all fields and separately from the current solution (e.g. to generate special Builders with setters which will ensure that everything was initialized). Such solution will keep things as simple as possible and will offer desired functionality only if needed. What do you think?

**Comment by Mi-La** [comment]
Note that if `index()` returned the `Enum` type, it would return non-existent enum value in case of uninitialized state. This seems to be quite an evil. Consider e.g. that a user will use switch with cases which will cover all the enum items - neither static analyzers nor compilers will complain and still there will be one uncovered case - the non-existing enum value returned by the index method.

**Comment by reinco** [comment]
If you follow my idea, index() should throw zserio::NotInitializedException if Unitialized. So similar to what visit() does in my example code.

I am not totally against exposing Uninitialized. That would mean adding it in the Enum and variant (either as monostate or preferrably a type Unitialized derived from monostate). However, then also a Visitor needs to deal with that and a user sees an enum additional to the choice types mentioned in the zserio script. So it seemed cleaner to deal with this by hiding the unitialized state and throw an exception whenever you try to access the variant. Note that this also happens with an std::variant. That also can be unitialized. See https://en.cppreference.com/w/cpp/utility/variant/valueless_by_exception.

However, if you would like to expose unitialized, RulesLaneRangeAttributeValue from my example would look like:
```cpp
namespace zserio { struct uninitialized : std::monostate{}; }
// Generate from choice RulesLaneRangeAttributeValue:
namespace RulesLaneRangeAttributeValue
{
    enum class Enum : size_t // enum names are from choice variable names below each case label NOT choice tags.
    {
        ZserioUninitialized = 0, // enum value for not initialized variant.
        ProhibitedPassage = 1,
        SpeedLimitKmh = 2,
        SpeedLimitMph = 3,
        LaneRightOfWayRegulation = 4
    };
    typedef zserio::variant<
        Enum,
        zserio::uninitialized   // uninitialized variant
        zserio::flag,               // type of case 1 from the choice
        zserio::uint8,              // type of case 2 from the choice
        zserio::uint8,              // type of case 3 from the choice
        LaneRightOfWayRegulation    // type of case 4 from the choice
    > Choice;
}
```

**Comment by Mi-La** [comment]
Ok, `index()` throwing an exception would be another deviation from `std::variant`, but why not. However it still seems cleaner to me to expose the uninitialized state to users.

Then it's a question what to do for choices which contain empty cases. Should we introduce another state `zserio::empty`, and have both `zserio::uninitialized` and `zserio::empty` variants? Or is it ok to leave only `zserio::empty` as a first (default) variant in that case?
In the old C++ generator I think that the choice remains always in `CHOICE_UNDEFINED` state in that case. So maybe having only `zserio::uninitalized` would be also ok. But then it would be probably good to allow to explicitly reset the variant to the uninitalized state.

**Comment by reinco** [comment]
I am fine with exposing the unitialized state if you think it is better. My only argument for using an exception is that a user is now forced to deal with a state that should not occur in well-behaved code.

About using zserio::empty instead of a dedicated zserio::unitialized: The only use case that comes to mind is a visitor that would throw if it sees unitialized. But probably it is not worth the trouble: std::variant also does not make the distinction between a 'value was never explicitly set' and empty.

Note that there will also be a type zserio::flag (which represents zserio language type 'Flag'. Although zserio::flag could just be an alias for zserio::empty).

**Comment by mikir** [comment]
Zserio optional has been fully implemented in the header [Variant.h](https://github.com/ndsev/zserio-cpp17/blob/master/runtime/src/zserio/Variant.h).
