### ISSUE TITLE
Array cannot be used in ranged for loop

### ISSUE THREAD

**Issue by MikeLankamp-TomTom** [ndsev/zserio-cpp17#52]
Generated C++ code for an array return `Array` from its `View`. `Array` does not have `begin` or `end` so cannot be iterated over. This prevents its usage in ranged for loops.

**Comment by Mi-La** [comment]
@MikeLankamp-TomTom
Please check current status. We added `begin()`, `end()` to the `Array`'s interface and implemented custom `ConstIterator` as an inner class. Since we return a temporary object (i.e. View) from `at()` method and thus it shall be also created when "dereferencing" iterator, it becomes slightly complicated and we are not 100% sure that the code is correct for all use-cases.

Note how the typedefs are defined in `ConstIterator`:
```
using iterator_category = std::random_access_iterator_tag;
using value_type = decltype(std::declval<Array>().at(std::declval<size_t>())); // this will be View<T> for compound types
using difference_type = std::ptrdiff_t;
/** Helper needed to implement operator-> on the ConstIterator. */
struct PointerHelper
{
    value_type* operator->()
    {
        return std::addressof(value);
    }
    value_type value;
};
using pointer = PointerHelper;
using reference = value_type; // we always use View by value!
```
See commit https://github.com/ndsev/zserio-cpp17/commit/a8bc544faa2b23225dedb8c6fe89c12c8f2fc46f for details.

Do you need also `rbegin()`, `rend()` on the `Array`'s interface? Or some other methods like `empty()`, `front()`, etc.?

**Comment by Mi-La** [comment]
Ok, we will add the rest of vector's public constant methods. 

Regarding performance and comparing only index - we will think about it.
Best practices - actually I took inspiration from boost's [`vector_const_iterator `](https://www.boost.org/doc/libs/1_50_0/boost/container/vector.hpp) and in this case I can't see any benefit making the operators friends - I still want to keep them inline since whole `ConstIterator` is an inner class of the `Array` template and I don't want to make complicated definitions outside of the class.

**Comment by MikeLankamp-TomTom** [comment]
> I don't want to make complicated definitions outside of the class.
There won't be any. You just declare the method `friend` in the class and write them as a non-member method, e.g.:
```
class ... {
  friend bool operator==(const ConstIterator& lhs, const ConstIterator& rhs) {
     return lhs.index == rhs.index;
  }
};
```
That's it. This is known as the "hidden friend idiom": https://www.justsoftwaresolutions.co.uk/cplusplus/hidden-friends.html. This improves performance on ADL-lookup, and it still avoids accidental implicit conversion.

**Comment by Mi-La** [comment]
> This improves performance on ADL-lookup.

I would appreciate some more detailed explanation or links on this topic. I don't believe it will have any remarkable effect in this case. And to be honest - just changing the methods to be friends without any practical benefit doesn't make sense to me, so I would like to understand what will be better.

**Comment by MikeLankamp-TomTom** [comment]
I posted a link in my comment, it explains the ADL part.
